<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalReactiveLockProjects)' != 'true'">
    <PackageReference Include="ReactiveLock.Core" Version="*-*" />
    <PackageReference Include="ReactiveLock.DependencyInjection" Version="*-*" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalReactiveLockProjects)' == 'true'">
    <ProjectReference Include="../../../../src/ReactiveLock.Core/ReactiveLock.Core.csproj" />
    <ProjectReference Include="../../../../src/ReactiveLock.DependencyInjection/ReactiveLock.DependencyInjection.csproj" />
  </ItemGroup>
</Project>
