name: k6 Test - Preview & Final

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: "NuGet package version to use"
        required: false
        default: "1.0.1-beta.1"

jobs:
  pack-nupkgs:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: built-nupkgs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Determine version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
            echo "Using version from input: $VERSION"
          else
            TAG_NAME="${GITHUB_REF##*/}"
            VERSION=$(echo "$TAG_NAME" | sed -E 's/^.*-v//')
            echo "Using version from Git tag: $VERSION"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Pack only (no push, skip tests)
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p ./nupkgs

          for projectDir in src/*/ ; do
            projectDir="${projectDir%/}"
            projectName=$(basename "$projectDir")
            csproj="$projectDir/$projectName.csproj"

            echo "Processing $projectName"

            if [ ! -f "$csproj" ]; then
              echo "❌ Skipping $projectName: No .csproj file found"
              continue
            fi

            if ! grep -q "<PackageId>" "$csproj"; then
              echo "⚠️ Skipping $projectName: <PackageId> not found"
              continue
            fi

            dotnet restore "$csproj"
            dotnet build "$csproj" --configuration Release --no-restore
            dotnet pack "$csproj" --configuration Release -p:PackageVersion=$VERSION -o ./nupkgs
          done

      - name: Upload nupkgs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-nupkgs
          path: ./nupkgs/*.nupkg
          retention-days: 1

  run-final-grpc-test:
    needs: pack-nupkgs
    uses: ./.github/workflows/k6-test-single.yml
    with:
      mode: 'final'
      project: 'grpc'

  run-preview-grpc-test:
    needs: pack-nupkgs
    uses: ./.github/workflows/k6-test-single.yml
    with:
      mode: 'preview'
      project: 'grpc'

  run-final-redis-test:
    needs: pack-nupkgs
    uses: ./.github/workflows/k6-test-single.yml
    with:
      mode: 'final'
      project: 'redis'

  run-preview-redis-test:
    needs: pack-nupkgs
    uses: ./.github/workflows/k6-test-single.yml
    with:
      mode: 'preview'
      project: 'redis'

  publish:
    needs: 
      - run-final-grpc-test
      - run-preview-grpc-test
      - run-final-redis-test
      - run-preview-redis-test
    runs-on: ubuntu-latest
    environment: nuget-publish
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-nupkgs
          path: ./nupkgs

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      #- name: Publish NuGet packages
      #  env:
      #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      #  run: |
      #    for pkg in ./nupkgs/*.nupkg; do
      #      echo "Publishing $pkg..."
      #      dotnet nuget push "$pkg" \
      #        --api-key $NUGET_API_KEY \
      #        --source https://api.nuget.org/v3/index.json \
      #        --skip-duplicate
      #    done