name: Publish NuGet Package

on:
  push:
    tags:
      - 'ReactiveLock.*-v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Parse package name and version from tag
        id: tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          PACKAGE_NAME=$(echo "$TAG_NAME" | sed -E 's/-v[0-9]+\.[0-9]+\.[0-9]+$//')
          VERSION=$(echo "$TAG_NAME" | sed -E 's/^.*-v//')

          echo "Package: $PACKAGE_NAME"
          echo "Version: $VERSION"

          echo "package=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and pack
        run: |
          PROJECT="src/${{ steps.tag.outputs.package }}/${{ steps.tag.outputs.package }}.csproj"
          dotnet restore "$PROJECT"
          dotnet build "$PROJECT" --configuration Release --no-restore
          dotnet pack "$PROJECT" \
            --configuration Release \
            -p:PackageVersion=${{ steps.tag.outputs.version }} \
            -o ./nupkgs

      - name: Push to NuGet
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate