name: Publish NuGet Package

on:
  push:
    tags:
      - 'ReactiveLock.*-v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Parse version from tag
        id: tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          VERSION=$(echo "$TAG_NAME" | sed -E 's/^.*-v//')
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build, pack and push all projects in src/
        run: |
          VERSION=${{ steps.tag.outputs.version }}

          # Loop through all top-level folders in src/
          for projectDir in src/*/ ; do
            # Remove trailing slash
            projectDir="${projectDir%/}"

            # Get project name assuming it's the same as folder name
            projectName=$(basename "$projectDir")
            csproj="$projectDir/$projectName.csproj"

            echo "Processing $projectName"

            dotnet restore "$csproj"
            dotnet build "$csproj" --configuration Release --no-restore
            dotnet pack "$csproj" --configuration Release -p:PackageVersion=$VERSION -o ./nupkgs

            dotnet nuget push "./nupkgs/${projectName}.$VERSION.nupkg" \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate
          done
