name: Build and Push Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: rinha-de-backend-2025-dotnet-csharp-redis
  SOURCE_FOLDER: src

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Docker Compose
        run: |
          cd ${{ env.SOURCE_FOLDER }}
          docker compose build

      - name: Tag image with timestamp
        id: tag
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:$TIMESTAMP
          docker tag ${{ env.IMAGE_NAME }} $IMAGE_TAG
          echo "Tagged image as $IMAGE_TAG"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Push Docker image to GHCR
        run: |
          docker push ${{ steps.tag.outputs.image_tag }}
